Repository konstellation-io/kdl-server, pull requests merged in 2021-11, with the labels that each got.

#647 fix(project-operator): Fix wrong object value in openAPIV3Schema
  helm/kdl-server/crds/project-operator-crd.yaml
Labels: bug

#654 fix(backup): Change resources value
  helm/kdl-server/values.yaml
Labels: bug

#650 feature: Change CI/CD
  .github/workflows/README.md
  .github/workflows/backup-component-build.yml
  .github/workflows/build-release.yml
  .github/workflows/cleaner-component-build.yml
  .github/workflows/drone-authorizer-component-build.yml
  .github/workflows/fix.yml
  .github/workflows/gitea-oauth2-setup-component-build.yml
  .github/workflows/helm-release.yml
  .github/workflows/jupyter-gpu-component-build.yml
  .github/workflows/kdl-server-app-api-quality.yml
  .github/workflows/kdl-server-app-dockerfile-quality.yml
  .github/workflows/kdl-server-app-ui-quality.yml
  .github/workflows/kdl-server-backup-quality.yml
  .github/workflows/kdl-server-cleaner-quality.yml
  .github/workflows/kdl-server-component-build.yml
  .github/workflows/kdl-server-drone-authorizer-quality.yml
  .github/workflows/kdl-server-gitea-oauth2-setup-quality.yml
  .github/workflows/kdl-server-jupyter-gpu-quality.yml
  .github/workflows/kdl-server-mlflow-quality.yml
  .github/workflows/kdl-server-project-operator-quality.yml
  .github/workflows/kdl-server-repo-cloner-quality.yml
  .github/workflows/kdl-server-user-tools-operator-quality.yml
  .github/workflows/kdl-server-vscode-quality.yml
  .github/workflows/mlflow-component-build.yml
  .github/workflows/new-release.yml
  .github/workflows/pre-release.yml
  .github/workflows/project-operator-component-build.yml
  .github/workflows/release.yml
  .github/workflows/repo-cloner-component-build.yml
  .github/workflows/user-tools-operator-component-build.yml
  .github/workflows/vscode-component-build.yml
  helm/kdl-server/templates/app/configmap.yaml
  helm/kdl-server/values.yaml
Labels: enhancement, github_actions

#662 feat(helm): Allow use custom TLS secret
  helm/kdl-server/templates/_helpers.tpl
  helm/kdl-server/templates/app/ingress.yaml
  helm/kdl-server/templates/drone/configmap.yaml
  helm/kdl-server/templates/drone/ingress.yaml
  helm/kdl-server/templates/drone/runner-deployment.yaml
  helm/kdl-server/templates/gitea/ingress.yaml
  helm/kdl-server/templates/gitea/statefulset.yaml
  helm/kdl-server/values.yaml
  scripts/kdlctl/cmd_deploy.sh
  scripts/kdlctl/cmd_login.sh
Labels: enhancement

#669 feat: Update workflow and add helm lint
  .github/workflows/backup-component-build.yml
  .github/workflows/cleaner-component-build.yml
  .github/workflows/drone-authorizer-component-build.yml
  .github/workflows/gitea-oauth2-setup-component-build.yml
  .github/workflows/helm-component.yml
  .github/workflows/helm-release.yml
  .github/workflows/jupyter-gpu-component-build.yml
  .github/workflows/kdl-server-component-build.yml
  .github/workflows/mlflow-component-build.yml
  .github/workflows/new-release.yml
  .github/workflows/project-operator-component-build.yml
  .github/workflows/repo-cloner-component-build.yml
  .github/workflows/user-tools-operator-component-build.yml
  .github/workflows/vscode-component-build.yml
  ct.yaml
  helmlintconf.yaml
Labels: enhancement

#665 feat: Update minio to use new chart
  ct.yaml
  helm/kdl-server/Chart.lock
  helm/kdl-server/Chart.yaml
  helm/kdl-server/templates/app/deployment.yaml
  helm/kdl-server/templates/common/tools-secret.yaml
  helm/kdl-server/templates/minio/ingress.yml
  helm/kdl-server/values.yaml
  helmlintconf.yaml
Labels: bug

#674 Fix: Remove fsgroup directive from backup-cronjob securityContext
  helm/kdl-server/templates/common/backup-cronjob.yaml
Labels: bug

#677 Fix: Update github workflows version
  .github/workflows/backup-component-build.yml
  .github/workflows/cleaner-component-build.yml
  .github/workflows/drone-authorizer-component-build.yml
  .github/workflows/gitea-oauth2-setup-component-build.yml
  .github/workflows/helm-component.yml
  .github/workflows/helm-release.yml
  .github/workflows/jupyter-gpu-component-build.yml
  .github/workflows/kdl-server-component-build.yml
  .github/workflows/mlflow-component-build.yml
  .github/workflows/new-release.yml
  .github/workflows/project-operator-component-build.yml
  .github/workflows/repo-cloner-component-build.yml
  .github/workflows/user-tools-operator-component-build.yml
  .github/workflows/vscode-component-build.yml
Labels: bug
