Repository konstellation-io/kdl-server, pull requests merged in 2022-04, with the labels that each got.

#783 fix(jupyter): Kernels must mount the shared-volume
  .github/workflows/helm-release.yml
  .pre-commit-config.yaml
  jupyter-kernelspecs/kernelspecs/kdl-py3.9-cuda10.2-cudnn7/scripts/kernel-pod.yaml.j2
  jupyter-kernelspecs/kernelspecs/kdl-py3.9/scripts/kernel-pod.yaml.j2
Labels: bug

#800 fix: define user-tools tls secret from values.yaml
  user-tools-operator/helm-charts/usertools/templates/_helpers.tpl
  user-tools-operator/helm-charts/usertools/templates/ingress.yaml
  user-tools-operator/helm-charts/usertools/templates/oauth2-proxy-configmap.yaml
  user-tools-operator/helm-charts/usertools/values.yaml
Labels: bug

#801 fix: pass the right tls secret name to MinIO and user-tools ingresses
  .github/workflows/helm-release.yml
  helm/kdl-server/crds/user-tools-operator-crd.yaml
  helm/kdl-server/templates/app/configmap.yaml
  helm/kdl-server/templates/minio/ingress-minio-console.yml
  helm/kdl-server/templates/minio/ingress-minio.yaml
Labels: bug

#802 fix: pass user-tools the name of the tls secret
  app/api/infrastructure/config/config.go
  app/api/infrastructure/k8s/kdlproject.go
  app/api/infrastructure/k8s/usertools.go
Labels: bug

#808 feature: pass ingress annotations from values.yaml
  user-tools-operator/helm-charts/usertools/templates/ingress.yaml
  user-tools-operator/helm-charts/usertools/values.yaml
Labels: enhancement

#806 feature: pass ingress annotations from values.yaml
  helm/kdl-server/crds/user-tools-operator-crd.yaml
  helm/kdl-server/templates/app/configmap.yaml
  helm/kdl-server/templates/app/ingress.yaml
  helm/kdl-server/templates/drone/ingress.yaml
  helm/kdl-server/templates/gitea/ingress.yaml
  helm/kdl-server/templates/minio/ingress-minio-console.yml
  helm/kdl-server/templates/minio/ingress-minio.yaml
  helm/kdl-server/values.yaml
Labels: enhancement

#807 feature: pass user-tools ingress annotations through userTools k8s resources
  app/api/infrastructure/config/config.go
  app/api/infrastructure/k8s/kdlproject.go
  app/api/infrastructure/k8s/usertools.go
Labels: enhancement

#811 fix: mlflow secret in app/api/templates/basic/.drone.yml.tmpl
  app/api/templates/basic/.drone.yml.tmpl
Labels: bug

#809 doc: Update Upgrading notes for 3.0.0 release
  README.md
Labels: documentation
