Repository konstellation-io/kdl-server, pull requests merged in 2024-10, with the labels that each got.

#985 chore(global): [KDL6-53] update and adds files to repository
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  helm/.gitignore
  helm/kdl-server/CHART.md
  helm/kdl-server/CHART.md.gotmpl
  helm/kdl-server/Chart.lock
  helm/kdl-server/Chart.yaml
  helm/kdl-server/README.md
  helm/kdl-server/README.md.gotmpl
  helm/kdl-server/UPGRADE_GUIDE.md
Labels: documentation

#989 docs(readme): [KDL6-62] update contributing with more info
  .github/workflows/auto-assign.yml
  .github/workflows/stale-issues-and-prs.yml
  CONTRIBUTING.md
Labels: documentation, devops-team, develop-team

#968 fix(api): [KDL6-27] serviceaccount in k8s 1.26
  .kdlctl.conf
  app/api/infrastructure/k8s/service_account.go
Labels: enhancement, develop-team

#994 ci(github): upgrade github action
  .github/.hadolint.yml
  .github/workflows/build-backup-component.yml
  .github/workflows/build-cleaner-component.yml
  .github/workflows/build-drone-authorizer-component.yml
  .github/workflows/build-gitea-oauth2-setup-component.yml
  .github/workflows/build-kdl-server-component.yml
  .github/workflows/build-mlflow-component.yml
  .github/workflows/build-project-operator-component.yml
  .github/workflows/build-repo-cloner-component.yml
  .github/workflows/build-user-tools-operator-component.yml
  .github/workflows/build-vscode-component.yml
  .github/workflows/component-build.yml
  .github/workflows/component-create-releases.yml
  .github/workflows/component-linter.yml
  .github/workflows/github-auto-assign.yml
  .github/workflows/helm-component.yml
  .github/workflows/helm-release.yml
  .github/workflows/new-release.yml
  .github/workflows/quality-check-kdl-server-api.yml
  .github/workflows/quality-check-kdl-server-ui.yml
  app/package.json
  backup/package.json
  cleaner/package.json
  drone-authorizer/package.json
  gitea-oauth2-setup/package.json
  mlflow/package.json
  package-lock.json
  package.json
  project-operator/package.json
  repo-cloner/package.json
  user-tools-operator/package.json
  vscode/package.json
Labels: enhancement, github_actions, develop-team
